DROP TABLE IF EXISTS `od-transfer`;
DROP TABLE IF EXISTS `od-trip`;
DROP TABLE IF EXISTS `od-trip-nodestination`;

CREATE TABLE `od-transfer` (
  `id`  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `csn` varchar(255) DEFAULT NULL,
  `bid` varchar(255) DEFAULT NULL,
  `transfer_boarding_date` date DEFAULT NULL,
  `transfer_boarding_time` time DEFAULT NULL,
  `origin_mode` int(11) DEFAULT NULL,
  `destination_mode` int(11) DEFAULT NULL,
  `num_passengers` int(11) DEFAULT NULL,
  `passenger_type` int(11) DEFAULT NULL,
  `product_id` int(11) DEFAULT NULL,
  `first_direction` varchar(255) DEFAULT NULL,
  `first_route_taken` varchar(255) DEFAULT NULL,
  `first_service_provider` int(11) DEFAULT NULL,
  `first_trip_id` varchar(255) DEFAULT NULL,
  `exit_stop_id` varchar(255) DEFAULT NULL,
  `exit_time` varchar(255) DEFAULT NULL,
  `exit_lat` varchar(255) DEFAULT NULL,
  `exit_lon` varchar(255) DEFAULT NULL,
  `transfer_boarding_stop_id` varchar(255) DEFAULT NULL,
  `transfer_stop_lat` varchar(255) DEFAULT NULL,
  `transfer_stop_lon` varchar(255) DEFAULT NULL,
  `transfer_route_taken` varchar(12) DEFAULT NULL,
  `transfer_direction` varchar(255) DEFAULT NULL,
  `transfer_newservice_provider` varchar(12) DEFAULT NULL,
  `number_of_transfers` int(11) DEFAULT NULL,
  `transfer_to_vehicle_id` varchar(255) DEFAULT NULL,
  `last_trip_id` varchar(12) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `od-trip` (
  `id`  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `csn` varchar(255) DEFAULT NULL,
  `bid` varchar(255) DEFAULT NULL,
  `trip_start_date` date DEFAULT NULL,
  `trip_start_time` time DEFAULT NULL,
  `origin_mode` varchar(12) DEFAULT NULL,
  `destination_mode` varchar(12) DEFAULT NULL,
  `num_passengers` int(11) DEFAULT NULL,
  `passenger_type` int(11) DEFAULT NULL,
  `product_id` int(11) DEFAULT NULL,
  `first_direction` varchar(12) DEFAULT NULL,
  `first_route_taken` varchar(64) DEFAULT NULL,
  `first_service_provider` int(11) DEFAULT NULL,
  `origin` varchar(255) DEFAULT NULL,
  `origin_service_agency` varchar(12) DEFAULT NULL,
  `origin_lat` varchar(255) DEFAULT NULL,
  `origin_lon` varchar(255) DEFAULT NULL,
  `destination` varchar(255) DEFAULT NULL,
  `destination_service_agency` varchar(12) DEFAULT NULL,
  `destination_lat` varchar(255) DEFAULT NULL,
  `destination_lon` varchar(255) DEFAULT NULL,
  `destination_time` varchar(32) DEFAULT NULL,
  `last_route_taken` varchar(32) DEFAULT NULL,
  `last_direction` varchar(12) DEFAULT NULL,
  `last_service_provider` varchar(32) DEFAULT NULL,
  `last_mode` varchar(32) DEFAULT NULL,
  `number_of_transfers` int(11) DEFAULT NULL,
  `last_vehicle_id` varchar(255) DEFAULT NULL,
  `last_trip_id` varchar(32) DEFAULT NULL,
  `transfer_required` varchar(32) DEFAULT NULL,
  `trip_start` varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `od-trip-nodestination` (
  `id`  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `csn` varchar(255) DEFAULT NULL,
  `bid` varchar(255) DEFAULT NULL,
  `trip_start_date` date DEFAULT NULL,
  `trip_start_time` time DEFAULT NULL,
  `origin_mode` varchar(12) DEFAULT NULL,
  `destination_mode` varchar(12) DEFAULT NULL,
  `num_passengers` int(11) DEFAULT NULL,
  `passenger_type` int(11) DEFAULT NULL,
  `product_id` int(11) DEFAULT NULL,
  `first_direction` varchar(12) DEFAULT NULL,
  `first_route_taken` varchar(64) DEFAULT NULL,
  `first_service_provider` int(11) DEFAULT NULL,
  `origin` varchar(255) DEFAULT NULL,
  `origin_service_agency` varchar(12) DEFAULT NULL,
  `origin_lat` varchar(255) DEFAULT NULL,
  `origin_lon` varchar(255) DEFAULT NULL,
  `destination` varchar(255) DEFAULT NULL,
  `destination_service_agency` varchar(12) DEFAULT NULL,
  `destination_lat` varchar(255) DEFAULT NULL,
  `destination_lon` varchar(255) DEFAULT NULL,
  `destination_time` varchar(32) DEFAULT NULL,
  `last_route_taken` varchar(32) DEFAULT NULL,
  `last_direction` varchar(12) DEFAULT NULL,
  `last_service_provider` varchar(32) DEFAULT NULL,
  `last_mode` varchar(32) DEFAULT NULL,
  `number_of_transfers` int(11) DEFAULT NULL,
  `last_vehicle_id` varchar(255) DEFAULT NULL,
  `last_trip_id` varchar(32) DEFAULT NULL,
  `transfer_required` varchar(32) DEFAULT NULL,
  `trip_start` varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8