create table if not exists `pt-avl`(
	`ID`					INT unsigned AUTO_INCREMENT KEY,
	`current_route_id` 		SMALLINT unsigned,
    `TransitDateValue`		DATE, 
    `apc_date_time`			DATETIME,
    `block_id`				SMALLINT unsigned,
    `direction_description`	VARCHAR(12),
    `StartTripTime_Trip`	TIME,
    `ons`					SMALLINT unsigned,
    `offs`					SMALLINT unsigned,
    `GPS_LOCATION`			POINT NOT NULL,
    `bs_sname`				SMALLINT unsigned,
    `bs_lname`				VARCHAR(256),
    `Month`					SMALLINT,
    `ext_trip_id`			MEDIUMINT unsigned,
    `Duplicate`				VARCHAR(10),
    `description`			VARCHAR(12),
    `sched_version`			SMALLINT unsigned,
    `TripCount`				SMALLINT unsigned,
    `import_error`			SMALLINT unsigned,
    `import_trip_error`		SMALLINT unsigned,
    `TripStartHour`			SMALLINT unsigned,

    INDEX (`current_route_id`),
    INDEX (`TransitDateValue`),
    INDEX (`apc_date_time`),
    INDEX (`direction_description`),
    INDEX (`StartTripTime_Trip`),
    INDEX (`ext_trip_id`),
    SPATIAL INDEX (`GPS_LOCATION`)
) ENGINE=MyISAM;